// Generated by FlutterFire CLI — Firebase project: lvs-demo
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web platform not configured');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2Xpjx1xRuZD7FeUkAOp-4x30V75vJgw',
    appId: '1:726301720796:android:f8c97a8c41aba4bbd33419',
    messagingSenderId: '726301720796',
    projectId: 'lvs-demo',
    storageBucket: 'lvs-demo.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXwVHf3kaFMcUFIl3kXkbFECJcBA-vR6U',
    appId: '1:726301720796:ios:ef99295b40c67a2cd33419',
    messagingSenderId: '726301720796',
    projectId: 'lvs-demo',
    storageBucket: 'lvs-demo.firebasestorage.app',
    androidClientId: '726301720796-m2o6576menbop4hkmbb31c0ilf5ggbok.apps.googleusercontent.com',
    iosClientId: '726301720796-rgv6r0u13nchpri2ht5nbdvss3usf940.apps.googleusercontent.com',
    iosBundleId: 'com.lvsinnovation.aliveApp',
  );
}
